filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/postgresql/*.log
  fields:
    type: postgresql
  fields_under_root: true
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /app/logs/application.log
  fields:
    type: application
    format: plain
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - /app/logs/application-json.log
  fields:
    type: application
    format: json
  fields_under_root: true
  json.keys_under_root: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "postgresql-%{+yyyy.MM.dd}"
      when.equals:
        type: "postgresql"
    - index: "application-%{+yyyy.MM.dd}"
      when.equals:
        type: "application"

setup.kibana:
  host: "kibana:5601"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644